name: Condo-Backend Push Workflow - Build and run tests

on:
  push:
    paths:
      - "condo-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SERVICE_ACCOUNT_KEYS: ${{ secrets.SERVICE_ACCOUNT_KEYS }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: condo-backend
      - name: Run Tests
        run: npm test
        working-directory: condo-backend
